### ISSUE TITLE
Frontend: Read from api and render 

### ISSUE THREAD

**Issue by thapakazi** [dibyahub/dec26-app#5]
## tasks

- [ ] get data from `/data` endpoint
- [ ] renders on browser
- [ ] updates data via websocket
